### ISSUE TITLE
digi_nrg_6chan32 has no access to power factor or reactive power

### ISSUE THREAD

**Issue by mim212** [digiblur/digiNRG_ESPHome#1]
It seems that while the splitcore implimentation of atm90e32as impliments power factor and reactive power for each phase, these are not available on the 6 channel version. My understanding is they both utilise the same chip (atm90e32as) and hense both reference the same registers over spi, but for some reason the registers are not available on the 6 channel version?

Ive included a log printout from esphome along with the added lines of code to include the reactive power and power factor into the yaml;

`sensor:
  - platform: wifi_signal
    name: ${disp_name} WiFi
    update_interval: 60s
  - platform: atm90e32
    cs_pin: 5
    phase_a:
      **reactive_power:
        name: ${disp_name} Reactive Power
        id: ic1ReactivePower
      power_factor:
        name: ${disp_name} Power Factor
        id: ic1PowerFactor**
      voltage:
        name: ${disp_name} Volts A
        id: ic1Volts
        accuracy_decimals: 1
      current:
        name: ${disp_name} CT1 Amps
        id: ct1Amps
      gain_voltage: 27845
# Voltage using a 9VAC power transformer
# Note: If you can not get the voltage correct with the highest gain of 65535, uncomment the 2.0 multiply filter above and lower the gain as needed
      gain_ct: 25753`

`INFO Reading configuration /config/esphome/mcu_powermeter.yaml...
INFO Detected timezone 'AEDT' with UTC offset 11
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/mcu_powermeter
Processing mcu_powermeter (board: nodemcu-32s; framework: arduino; platform: espressif32@1.11.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
Dependency Graph
|-- <AsyncTCP-esphome> 1.1.1
|-- <ESPmDNS> 1.0
|   |-- <WiFi> 1.0
|-- <FS> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.6
|   |-- <AsyncTCP-esphome> 1.1.1
|   |-- <FS> 1.0
|   |-- <WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <Update> 1.0
|-- <WiFi> 1.0
|-- <SPI> 1.0
Compiling /data/mcu_powermeter/.pioenvs/mcu_powermeter/src/main.cpp.o
Archiving /data/mcu_powermeter/.pioenvs/mcu_powermeter/lib715/libAsyncTCP-esphome_ID6798.a
Compiling /data/mcu_powermeter/.pioenvs/mcu_powermeter/lib789/WiFi/WiFiClient.cpp.o
Compiling /data/mcu_powermeter/.pioenvs/mcu_powermeter/lib789/WiFi/WiFiGeneric.cpp.o
Compiling /data/mcu_powermeter/.pioenvs/mcu_powermeter/lib789/WiFi/WiFiMulti.cpp.o
Compiling /data/mcu_powermeter/.pioenvs/mcu_powermeter/lib789/WiFi/WiFiSTA.cpp.o
src/main.cpp: In function 'void setup()':
src/main.cpp:597:31: error: 'class esphome::atm90e32::ATM90E32Component' has no member named 'set_react_pow_sensor'
   atm90e32_atm90e32component->set_react_pow_sensor(0, ic1ReactivePower);
                               ^
src/main.cpp:609:31: error: 'class esphome::atm90e32::ATM90E32Component' has no member named 'set_pf_sensor'
   atm90e32_atm90e32component->set_pf_sensor(0, ic1PowerFactor);
                               ^
Compiling /data/mcu_powermeter/.pioenvs/mcu_powermeter/lib789/WiFi/WiFiScan.cpp.o
Compiling /data/mcu_powermeter/.pioenvs/mcu_powermeter/lib789/WiFi/WiFiServer.cpp.o
*** [/data/mcu_powermeter/.pioenvs/mcu_powermeter/src/main.cpp.o] Error 1
========================== [FAILED] Took 5.88 seconds ==========================`

**Comment by digiblur** [comment]
Please open the issue on ESPHome github.
