### ISSUE TITLE
Incorrect gain_pga settings in yaml example for using ct clamps over 65A 

### ISSUE THREAD

**Issue by invinciberry** [digiblur/digiNRG_ESPHome#4]
According to CiricuitSetup's Github 

>  The max value for current that the meter can output is 65.535. If you expect to measure current over 65A, 
>  divide the gain_ct by 2 (120A CT) or 4 (200A CT) and multiply the current and power values by 2 or 4 by uncommenting the filter below

So for measuring and using CT clamps over 65A, gain_pga should be 1X and an additional x2 multiplier is needed under the current sensor to produce a correct reading.

**Comment by Teleportist** [comment]
This comment only applies if you will actually be measuring currents >65A.
This is regardless of the rating of your CT clamps, but obviously you need to be using a clamp capable of reading the maximum current of the circuit in question.

So, for example, you found that you were regularly seeing readings of 65A on a circuit, but no higher, then you can use this method (dividing the gain by 2) to bring the readings down to a level <65A.

Say your gain (current_cal:) is currently 28,000 and circuit current is 70A. If you half this to 14,000 your sensor will be reporting 35A.

To correct this, then multiply the values of your sensors by 2, by adding the filters shown in the code example below.
Replace '?' with whatever channel number applies.

     phase_?:
      current:
        name: ${disp_name} CT? Amps
        id: ct?Amps
        filters:
          - multiply: 2
      power:
        name: ${disp_name} CT? Watts
        id: ct?Watts
        filters:
          - multiply: 2
      gain_voltage: ${voltage_cal}
      gain_ct: ${current_cal}


Bit of a late answer, I know, but I've only just started with this board. Hope it helps.
