### ISSUE TITLE
Feature Request: Sensor Data from Both Chips to Publish at the Same Time.

### ISSUE THREAD

**Issue by Teleportist** [digiblur/digiNRG_ESPHome#5]
Firstly, thanks for this implemetation, which I've now been using for a couple of months.

However, I have one remaining issue, which is proving a real pain to resolve.
I have a sensor which is calculated by subtracting one clamp from another.
Unfortunately the clamps in question are on different chips of the board, which don't update at the same time.
This means that it's possible for the calculated sensor to be a negative value. Hopefully the below screen grab from Grafana will clearly show the issue.

![image](https://user-images.githubusercontent.com/61894621/103577465-caf0b680-4ecc-11eb-8027-a8f88060f09d.png)

Total (CT1) = Incoming cable from the grid
Ground & 1st Floors (CT6) = Cable into primary fuse board
2nd Floor (calculated) = Should be what my separate fuse board, for the 2nd floor, is consuming. Total - Ground & 1st Floors.

I don't have a spare channel (using all 6) to actually clamp on to the cable into the secondary fuse board, which services the second floor.

Is there any way to ensure sensors on both channels/chips publish at the same time please?

Many thanks.

**Comment by digiblur** [comment]
That would be a feature/bug report on the ESPHome software github.

**Comment by Teleportist** [comment]
Apologies.

Have now raised this on the ESPHome site.
Here's a link for anyone wanting to track this.
https://github.com/esphome/feature-requests/issues/1087
